package com.c4hco.test.automation.Dto;

import com.c4hco.test.automation.Dto.Edi.Edi834.CommonEDISegments;
import com.c4hco.test.automation.Dto.Edi.Edi834.Edi834TransactionDetails;
import com.c4hco.test.automation.Dto.Edi.Edi999.Edi999Segments;
import com.c4hco.test.automation.database.EntityObj.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class SharedData {
    @Getter @Setter private static String firstPlanNameOnMedicalResultsPage;
    @Getter @Setter private static String firstPlanNameOnDentalResultsPage;
    @Getter @Setter private static String appType;
    @Getter @Setter private static MemberDetails primaryMember;
    @Getter @Setter private static List<MemberDetails> members;
    @Getter @Setter private static List<MemberDetails> allMembers; // should be removed
    @Getter @Setter private static List<Ob834DetailsEntity> ob834DetailsMedEntities;
    @Getter @Setter private static List<Ob834DetailsEntity> ob834DetailsDenEntities;
    @Getter @Setter private static List<PolicyTablesEntity> medicalPolicyTablesEntities;
    @Getter @Setter private static List<PolicyTablesEntity> dentalPolicyTablesEntities;
    @Getter @Setter private static String medicalFileName;
    @Getter @Setter private static String dentalFileName;
    @Getter @Setter private static List<String> medicalFileName_grp;
    @Getter @Setter private static List<String> dentalFileName_grp;
    @Getter @Setter private static List<Ib999Entity> ib999MedDetailsEntities;
    @Getter @Setter private static List<Ib999Entity> ib999DenDetailsEntities;
    @Getter @Setter private static List<Ib834Entity> ib834MedDetailsEntities;
    @Getter @Setter private static List<Ib834Entity> ib834DenDetailsEntities;
    @Getter @Setter private static String medicalIb999FileName;
    @Getter @Setter private static String dentalIb999FileName;
    @Getter @Setter private static List<String> medicalIb999FileNames;
    @Getter @Setter private static List<String> dentalIb999FileNames;
    @Getter @Setter private static String medicalIb834FileName;
    @Getter @Setter private static String dentalIb834FileName;
    @Getter @Setter private static List<String> medicalIb834FileNames;
    @Getter @Setter private static List<String> dentalIb834FileNames;
    @Getter @Setter private static String localPathToDownloadFile;
    @Getter @Setter private static Edi834TransactionDetails edi834TransactionDetails;
    @Getter @Setter private static Edi834TransactionDetails ib834TransactionDetails;
    @Getter @Setter private static CommonEDISegments commonEDISegments;
    @Getter @Setter private static Edi999Segments ib999Segments;
    @Getter @Setter private static Edi999Segments ob999Segments;
    @Getter @Setter private static CommonEDISegments ib834Segments;
    @Getter @Setter private static String env;
    @Getter @Setter private static DbData dbData;
    @Getter @Setter private static Map<String, PlanDbData> medicalPlanDbData;
    @Getter @Setter private static Map<String, PlanDbData> dentalPlanDbData;
    @Getter @Setter private static Set<Map<String, DbData>> dbDataNew;
    @Getter @Setter private static List<Map<String, PlanDbData>> medicalPlanDbDataNew;
    @Getter @Setter private static List<Map<String, PlanDbData>> dentalPlanDbDataNew;
    @Getter @Setter private static String carrierPdfFileName;
    @Getter @Setter private static String planYear;
    @Getter @Setter private static GroupDetails groupDetails;
    @Getter @Setter private static String dbName;
    @Getter @Setter private static String isOpenEnrollment;
    @Getter @Setter private static String ses;
    @Getter @Setter private static Map<String, String> memIdAndMedicalFileName;
    @Getter @Setter private static Map<String, String> memIdAndDentalFileName;
    @Getter @Setter private static Boolean hasBroker = false;
    @Getter @Setter private static BrokerDetails agencyOwner;
    @Getter @Setter private static BrokerDetails broker;
    @Getter @Setter private static BrokerDetails adminStaff;
    @Getter @Setter private static AssisterDetails programManager;
    @Getter @Setter private static String noticeFileName;
    @Getter @Setter private static List<BookOfBusinessQEntity> bookOfBusinessQEntityList;
    @Getter @Setter private static Map<String, List<String>> groupingDetails;
    @Getter @Setter private static ScenarioDetails scenarioDetails;
    @Getter @Setter private static String medGroupCtlNumber;
    @Getter @Setter private static String denGroupCtlNumber;
    @Getter @Setter private static Set<String> medGroupCtlNumbers;
    @Getter @Setter private static List<String> denGroupCtlNumbers;
    @Getter @Setter private static List<String> medicalPlansList;
    @Getter @Setter private static List<String> dentalPlansList;
    @Getter @Setter private static Map<String, String> calculatedDob;
    @Getter @Setter private static Map<String, String> transForGrpCtrlNum;
    @Getter @Setter private static Map<String, String> ib834transForGrpCtrlNum;
    @Getter @Setter private static ExpectedCalculatedDates expectedCalculatedDates_medicalPlan;
    @Getter @Setter private static ExpectedCalculatedDates expectedCalculatedDates_dentalPlan;
    @Getter @Setter private static Map<String, String> exchPersonId;
    @Getter @Setter private static String birthLceIndividual;
    @Getter @Setter private static ManagePlanDentalMedicalPlan managePlanDentalMedicalPlan;
    @Getter @Setter private static List<String> dvrDateTime;
    @Getter @Setter private static List<String> EventIds;
    @Getter @Setter private static List<Ob999Entity> ob999MedDetailsEntities;
    @Getter @Setter private static List<Ob999Entity> ob999DenDetailsEntities;
    @Getter @Setter private static String medicalOb999FileName;
    @Getter @Setter private static String dentalOb999FileName;
    @Getter @Setter private static List<String> medicalOb999FileNames;
    @Getter @Setter private static List<String> dentalOb999FileNames;
    @Getter @Setter private static AdminDetails adminDetails;
    @Getter @Setter private static String primaryTaxPayerKey;
    @Getter @Setter private static BigDecimal oldAccountId;
    @Getter @Setter private static AssisterDetails assisterDetails;
    @Getter @Setter private static List<String> Companyname;
    @Getter @Setter private static String FinancialIncome;
    @Getter @Setter private static String EffectiveLCEDate;

    @Getter @Setter private static Boolean isAiAn = false;
    @Getter @Setter private static String recType = null;

    public static void reset(){
        firstPlanNameOnMedicalResultsPage = null;
        firstPlanNameOnDentalResultsPage = null;
        appType = null;
        primaryMember = null;
        members = null;
        edi834TransactionDetails = null;
        commonEDISegments = null;
        env = null;
        dbData = null;
        dbDataNew = null;
        medicalPlanDbDataNew = null;
        dentalPlanDbDataNew = null;
        planYear = null;
        groupDetails = null;
        dbName = null;
        noticeFileName = null;
        bookOfBusinessQEntityList = null;
        isOpenEnrollment = null;
        ses = null;
        scenarioDetails = null;
        ib999Segments = null;
        medicalPlansList=null;
        dentalPlansList=null;
        calculatedDob = null;
        exchPersonId=null;
        birthLceIndividual = null;
        allMembers = null;
        medicalPolicyTablesEntities = null;
        dentalPolicyTablesEntities = null;
        ob834DetailsMedEntities = null;
        ob834DetailsDenEntities = null;
        dvrDateTime = null;
        EventIds = null;
        ob999MedDetailsEntities = null;
        ob999DenDetailsEntities = null;
        medicalOb999FileName = null;
        dentalOb999FileName = null;
        ob999Segments = null;
        ib834TransactionDetails=null;
        expectedCalculatedDates_medicalPlan = null;
        expectedCalculatedDates_dentalPlan = null;
        oldAccountId = null;
        primaryTaxPayerKey=null;
        transForGrpCtrlNum = null;
        medGroupCtlNumbers = null;
        denGroupCtlNumbers = null;
        Companyname = null;
        FinancialIncome = null;
        EffectiveLCEDate = null;
        isAiAn = false;
        recType = null;
        carrierPdfFileName = null;
    }

}