package com.c4hco.test.automation.pages.cocoPages;

import com.c4hco.test.automation.utils.BasicActions;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.testng.asserts.SoftAssert;

public class TermsOfUseCoCoPage {

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[1]")
    WebElement title;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/p")
    WebElement p1;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[1]")
    WebElement ol1;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[2]")
    WebElement ol2;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[3]")
    WebElement ol3;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[4]")
    WebElement ol4;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[5]")
    WebElement ol5;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[6]")
    WebElement ol6;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[7]")
    WebElement ol7;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[8]")
    WebElement ol8;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[1]/li[8]/p[2]")
    WebElement p2;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[2]/li[1]")
    WebElement ol9;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[2]/li[2]")
    WebElement ol10;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[3]/li[1]")
    WebElement ol11;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[3]/li[2]")
    WebElement ol12;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[3]/li[3]")
    WebElement ol13;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[3]/li[4]")
    WebElement ol14;

    @FindBy(xpath = "/html/body/app-root/div/div/div/app-terms-of-use/app-container/div/div/div[2]/div/ol[3]/li[5]")
    WebElement ol15;

    SoftAssert softAssert = new SoftAssert();
    private BasicActions basicActions;


    public TermsOfUseCoCoPage(WebDriver webDriver) {
        basicActions = new BasicActions(webDriver);
        PageFactory.initElements(basicActions.getDriver(), this);
    }


    public void verifyPageText(String language) {

        switch (language) {
            case "English":
                verifyEnglish();
                break;
            case "Spanish":
                verifySpanish();
                break;
            default: throw new IllegalArgumentException("Unsupported language: " + language);
        }

    }

    private void verifySpanish() {

        softAssert.assertEquals(title.getText(), "T\u00E9rminos de uso");
        softAssert.assertEquals(p1.getText(), "Bienvenido a los sitios web de Colorado Connect (el \u201CSitio\u201D). Este Sitio es operado por Connect for Health Colorado, una corporaci\u00F3n de Colorado cuyo nombre comercial es Colorado Connect (\u201CNosotros\u201D). S\u00EDrvase leer atentamente estos t\u00E9rminos de uso. Al usar el Sitio, usted reconoce y acepta haber le\u00EDdo y accedido a regirse por estos t\u00E9rminos de uso (este \u201CAcuerdo\u201D). Este Acuerdo se realiza entre Colorado Connect y Usted o, en caso de que usted represente y use el Sitio en nombre de una compa\u00F1\u00EDa u otra entidad, esa compa\u00F1\u00EDa u otra entidad (\u201CUsted\u201D). SI NO ACCEDE A REGIRSE POR ESTE ACUERDO, HAGA FAVOR DE ABANDONAR EL SITIO Y ABSTENERSE DE UTILIZAR CUALQUIER MATERIAL QUE PUEDA HABER DESCARGADO DEL SITIO.");
        softAssert.assertEquals(ol1.getText().trim(), "USO DE ESTE SITIO. Todo uso del Sitio est\u00E1 sujeto a los t\u00E9rminos de este Acuerdo. Usted puede acceder y usar el Sitio \u00FAnicamente para fines contemplados por la ley. Debe tener 13 a\u00F1os de edad o m\u00E1s para usar este Sitio. Cuando as\u00ED lo estime procedente y a su exclusivo criterio, Colorado Connect se reserva el derecho de modificar, suspender o interrumpir el Sitio (o cualquier parte de este) con o sin aviso.");
        softAssert.assertEquals(ol2.getText().trim(), "REGISTRO. Para obtener acceso a ciertas partes del Sitio, Usted podr\u00EDa tener que solicitar que se le designe usuario registrado (\u201CUsuario Registrado\u201D) del Sitio, y que se apruebe su solicitud. La aprobaci\u00F3n de su solicitud como Usuario Registrado queda al exclusivo criterio de Colorado Connect. Despu\u00E9s que se apruebe su solicitud como Usuario Registrado, podr\u00EDa ped\u00EDrsele que cree una cuenta protegida con contrase\u00F1a (una \u201CCuenta\u201D). Usted accede a mantener la confidencialidad de la informaci\u00F3n y contrase\u00F1a de su Cuenta. Usted accede a notificar a Colorado Connect de inmediato si ocurre un uso no autorizado de su Cuenta, real o presunto. Usted es exclusivamente responsable de todo lo que ocurra en torno a su Cuenta. Colorado Connect no ser\u00E1 responsable de ninguna p\u00E9rdida o da\u00F1o que le sobrevenga a Usted por no cumplir con estas obligaciones. En relaci\u00F3n con su solicitud para convertirse en Usuario Registrado, se le pedir\u00E1 que proporcione cierta informaci\u00F3n acerca de Usted (\u201CInformaci\u00F3n de Registro\u201D). Usted declara y garantiza que: (a) toda la Informaci\u00F3n de Registro que Usted proporcione es verdadera, correcta, actual y completa; y (b) que Usted mantendr\u00E1 y actualizar\u00E1 r\u00E1pidamente la Informaci\u00F3n de Registro a fin de que sea siempre verdadera, correcta, actual y completa. Como parte del proceso de registro, podr\u00EDa asign\u00E1rsele o permit\u00EDrsele que cree una identificaci\u00F3n de usuario que sirva para identificar su Cuenta (un \u201CID de Usuario\u201D). Usted no podr\u00E1: (i) seleccionar o usar un ID de Usuario de otra persona con el fin de hacerse pasar por esa persona; (ii) usar un ID de Usuario sobre el cual otra persona tenga derecho sin la autorizaci\u00F3n de esa persona; o (iii) usar un ID de Usuario que, al exclusivo criterio de Colorado Connect, resulte ofensivo. Si no cumple con lo anterior, se considerar\u00E1 que ha faltado a este Acuerdo, lo que puede conducir a la cancelaci\u00F3n inmediata de su Cuenta.");
        softAssert.assertEquals(ol3.getText().trim(), "VIGENCIA Y FINALIZACI\u00D3N. Este Acuerdo entrar\u00E1 en vigor en la fecha en que Usted utilice por primera vez el Sitio y continuar\u00E1 hasta su finalizaci\u00F3n. Colorado Connect puede finalizar o modificar este Acuerdo inmediatamente, por cualquier raz\u00F3n o sin motivo alguno, con o sin aviso para Usted. Usted puede finalizar este Acuerdo enviando un aviso escrito a Colorado Connect, quien lo cancelar\u00E1 al momento de recibir la notificaci\u00F3n. Colorado Connect puede tambi\u00E9n suspender su uso del Sitio o desactivar su ID de Usuario y ordenarle que deje de usar el Sitio, con o sin aviso para Usted y con o sin causa. Al ocurrir cualquier finalizaci\u00F3n de este Acuerdo, cesar\u00E1n todos los derechos concedidos a Usted conforme a los t\u00E9rminos de este acuerdo y Usted deber\u00E1 interrumpir a la brevedad todo acceso a cualquier parte del Sitio, y el uso de cualquier Contenido descargado u obtenido de otra manera del Sitio. Las secciones 3, 4, 5, 7, 10, 11 y 15 sobrevivir\u00E1n a la finalizaci\u00F3n o vencimiento de este Acuerdo por cualquier raz\u00F3n, conforme se aplican al derecho concedido a Colorado Connect y las restricciones impuestas a Usted.");
        softAssert.assertEquals(ol4.getText().trim(), "CONTENIDO: El Sitio y todo su contenido, como son, entre otros, texto, archivos, im\u00E1genes, gr\u00E1ficos, ilustraciones, audio, video y fotograf\u00EDas contenidos u ofrecidos a trav\u00E9s del Sitio (en conjunto, \u201CContenido\u201D) est\u00E1n protegidos por derechos de propiedad intelectual, lo que incluye, seg\u00FAn sea pertinente y sin limitaci\u00F3n, derechos de autor, marcas registradas, patentes y otros derechos de posesi\u00F3n y de propiedad intelectual (\u201CDerechos de Propiedad Intelectual\u201D) de Colorado Connect o terceros que han cedido sus derechos a Colorado Connect.");
        softAssert.assertEquals(ol5.getText().trim(), "USO DEL CONTENIDO. Su acceso al Contenido y el uso de este est\u00E1n sujetos a los t\u00E9rminos y condiciones del presente Acuerdo. Usted puede utilizar el Contenido solamente en la forma en que se proporciona en el Sitio o a trav\u00E9s de \u00E9l, solamente para sus propios prop\u00F3sitos de informaci\u00F3n. No podr\u00E1 utilizar ning\u00FAn Contenido con ning\u00FAn prop\u00F3sito comercial, ni cobrar honorarios ni otra retribuci\u00F3n a cambio del Contenido. No podr\u00E1 utilizar el Contenido para vender, anunciar, avalar ni promover de otra manera ning\u00FAn otro servicio, producto o partido. Todo el uso del Contenido debe acompa\u00F1arse del reconocimiento de que es propiedad de Colorado Connect. Por lo dem\u00E1s, Usted deber\u00E1 respetar todos los Derechos de Propiedad Intelectual, avisos, informaci\u00F3n o restricciones referentes o inherentes a cualquier Contenido. A menos que se especifique otra cosa en el Sitio, como entre Usted y Colorado Connect, sus socios, afiliados y licenciatarios (\u201CAfiliados\u201D), todo el Contenido es propiedad de Colorado Connect y sus Afiliados. Salvo por lo que se indique en este Acuerdo, no se le conceden licencias ni derechos, ni por implicaci\u00F3n, impedimento ni de otra manera, en o respecto al Sitio o su Contenido, ni ning\u00FAn Derecho de Propiedad Intelectual impl\u00EDcito ni relacionado con estos, y no podr\u00E1 modificar, reproducir, ejecutar, mostrar, crear trabajos derivados, republicar, publicar, transmitir ni participar en la transferencia, venta o distribuci\u00F3n, ni de ninguna manera explotar cualquier parte del Sitio o Contenido, sin el permiso escrito previo de Colorado Connect. Si Usted quisiera utilizar el Contenido de una manera que no se haya establecido expresamente en este Acuerdo, comun\u00EDquese con Nosotros a trav\u00E9s de la p\u00E1gina \u201CP\u00F3ngase en contacto\u201D.");
        softAssert.assertEquals(ol6.getText().trim(), "MARCAS. A menos que se indique lo contrario, todas las marcas registradas, marcas de servicios, logotipos, banners y encabezados que aparecen en este Sitio (en conjunto, las \u201CMarcas\u201D) son propiedad de Colorado Connect y sus Afiliados. Salvo por lo que se establece expresamente en este Acuerdo, no podr\u00E1 mostrar, enlazarse ni utilizar las Marcas de otra manera, sin previo permiso por escrito de Colorado Connect.");
        softAssert.assertEquals(ol7.getText().trim(), "PUBLICACIONES Y CARGAS. El Sitio puede incluir foros, pizarras de anuncios, salas de chat u otros recursos mediante los cuales puede Usted proporcionar o cargar su propio contenido al Sitio. Usted se compromete a no subir o proporcionar ning\u00FAn Contenido que sea: (1) falso, difamatorio, obsceno, abusivo, pornogr\u00E1fico, amenazante o una invasi\u00F3n a la privacidad; (2) una infracci\u00F3n al Derecho de Propiedad Intelectual de cualquier tercero; (3) ilegal de alguna manera o que favorezca la actividad ilegal; (4) un anuncio o petici\u00F3n de valores, bienes o servicios; (5) un apoyo o anuncio de cualquier candidato a un cargo p\u00FAblico; (6) un virus o elemento inform\u00E1tico que contenga cualquier otro c\u00F3digo, archivo o programa de computadora que cause da\u00F1os. Nos reservamos el derecho a rechazar o retirar sin previo aviso cualquier publicaci\u00F3n o Contenido que a nuestro solo criterio infrinja esta Secci\u00F3n 7. Por este medio, Usted reconoce y garantiza a Colorado Connect y sus Afiliados que posee todo el derecho, autoridad e inter\u00E9s para publicar cualquier Contenido que proporcione o suba al Sitio, o que tiene suficiente derecho, sea por implicaci\u00F3n, preclusi\u00F3n o de otra manera, de publicar o subir Contenido y otorga a Colorado Connect los derechos que se detallan en esta Secci\u00F3n 7. Usted mantendr\u00E1 indemne, defender\u00E1 y exonerar\u00E1 a Colorado Connect y sus Afiliados de todas y cada una de las reclamaciones, p\u00E9rdidas, responsabilidades, da\u00F1os, multas, gastos y costos de terceros (incluso los honorarios de los abogados y las costas) resultantes de una infracci\u00F3n real o supuesta de cualquier declaraci\u00F3n o garant\u00EDa dispuesta en la Secci\u00F3n 7. Al proporcionar o subir cualquier Contenido al Sitio, Usted otorga a Colorado Connect un derecho no exclusivo, exento de regal\u00EDas, perpetuo, irrevocable y totalmente sublicenciable, para utilizar, copiar, almacenar, reproducir, modificar, mostrar, adaptar, publicar, traducir, crear trabajos derivados, distribuir y divulgar tal Contenido en todo el mundo, en cualquier forma, medios, software o tecnolog\u00EDa. Adem\u00E1s, renuncia a todo derecho moral sobre el Contenido, incluido cualquier Contenido que Usted publique o suba, o garantiza que se han cedido todos los derechos morales aplicables a dicho Contenido. Tambi\u00E9n otorga a Colorado Connect el derecho a utilizar Su nombre en relaci\u00F3n con la reproducci\u00F3n o distribuci\u00F3n de tal material.");
        softAssert.assertEquals(ol8.getText().trim(), "DENUNCIAS DE INFRACCI\u00D3N. As\u00ED como Colorado Connect solicita a los usuarios de su Sitio respetar los derechos de autor y otros Derechos de Propiedad Intelectual de Colorado Connect, sus Afiliados y terceros, Colorado Connect respeta los derechos de autor y otros Derechos de Propiedad Intelectual de los usuarios del Sitio y de terceros. Si Usted cree de buena fe que su trabajo protegido por derecho de autor se ha reproducido en el Sitio sin autorizaci\u00F3n de una manera que constituya infracci\u00F3n a los derechos de autor, puede Usted informar a nuestro agente de derechos de autor designado, escribiendo a:\n" +
                " \n" +
                "Colorado Connect\n" +
                "c/o Connect for Health Colorado\n" +
                "4600 S. Ulster Street, Suite 300\n" +
                "Denver, CO 80237\n" +
                "Proporcione la siguiente informaci\u00F3n a Colorado Connect:\n" +
                "(1) La identidad del trabajo objeto de la infracci\u00F3n y del presunto trabajo infractor;\n" +
                "(2) Su nombre, domicilio, n\u00FAmero telef\u00F3nico diurno y direcci\u00F3n de correo electr\u00F3nico, si tuviera;\n" +
                "(3) La declaraci\u00F3n de que Usted cree de buena fe que el uso del trabajo protegido por derechos de autor no est\u00E1 autorizado por su propietario o agente de este, ni por la ley;\n" +
                "(4) Una declaraci\u00F3n de la exactitud del aviso y, bajo pena de falso testimonio, que est\u00E1 Usted autorizado a actuar a nombre del propietario; y\n" +
                "(5) Su firma electr\u00F3nica o f\u00EDsica.");
        softAssert.assertEquals(ol9.getText().trim(), "RECONOCIMIENTOS Y GARANT\u00CDAS. Usted reconoce, garantiza y acuerda, por el beneficio de Colorado Connect y sus Afiliados, que: (1) Usted tiene el derecho y la autoridad legales para autorizar este Acuerdo y, si est\u00E1 aceptando este Acuerdo a nombre de una empresa o de otra entidad, para someter a la empresa u otra entidad a los t\u00E9rminos de este Acuerdo; (2) Usted tiene el derecho legal y la autoridad para cumplir con Sus obligaciones seg\u00FAn los t\u00E9rminos de este Acuerdo, y para otorgar los derechos y las licencias descritas en este Acuerdo y en cualquier acuerdo adicional aplicable en el que participe en relaci\u00F3n con cualquiera de los Servicios; (3) toda la informaci\u00F3n que proporcione a Colorado Connect en relaci\u00F3n con este Acuerdo y su acceso al Sitio y el uso de los Servicios es correcta y vigente.");
        softAssert.assertEquals(ol10.getText().trim(), "DESCARGO Y LIMITACI\u00D3N DE RESPONSABILIDAD.\n" +
                " \n" +
                "10.1 Descargo de responsabilidad. EL SITIO ES PROPORCIONADO POR Colorado Connect \u201CTAL CUAL\u201D y \u201CCOMO SE OFRECE\u201D, SIN NINGUNA GARANT\u00CDA. NI Colorado Connect NI SUS AFILIADOS RECONOCEN NI RESPALDAN LA EXACTITUD O CONFIABILIDAD DE NING\u00DAN CONSEJO, OPINI\u00D3N, DECLARACI\u00D3N U OTRA INFORMACI\u00D3N QUE SE MUESTRE, SE DESCARGUE O SE DISTRIBUYA A TRAV\u00C9S DEL SITIO. USTED ACEPTA QUE SU ACCESO AL SITIO ES BAJO SU PROPIO RIESGO Y QUE USTED ES EL \u00DANICO RESPONSABLE DE CUALQUIER AFECTACI\u00D3N O DA\u00D1O EN QUE USTED INCURRA MEDIANTE SU ACCESO AL SITIO. EXCEPTO CUANDO EXISTAN LEYES Y REGLAMENTOS DE UNA JURISDICCI\u00D3N PARTICULAR REFERENTE A GARANT\u00CDAS DE LAS QUE NO PUEDA EXIMIRSE O EXCLUIRSE POR ACUERDO, COLORADO CONNECT SE EXIME EXPRESAMENTE DE TODAS LAS GARANT\u00CDAS, EXPRESAS O IMPL\u00CDCITAS, RESPECTO AL SITIO, INCLUIDAS, SIN LIMITACI\u00D3N, TODAS LAS GARANT\u00CDAS DE AUTORIDAD, NO INFRACCI\u00D3N, COMERCIABILIDAD E IDONEIDAD PARA UN PROP\u00D3SITO PARTICULAR. USTED RECONOCE QUE EL ESTADO ACTUAL DE LA TECNOLOG\u00CDA NO PERMITE UN ACCESO AL SITIO EXENTO DE ERRORES Y QUE PUEDEN OCURRIR PERI\u00D3DICAMENTE INTERRUPCIONES, CA\u00CDDAS DEL SISTEMA Y TIEMPOS MUERTOS, FUERA DEL CONTROL DE COLORADO CONNECT.\n" +
                " \n" +
                "10.2 Limitaci\u00F3n. EN NING\u00DAN CASO COLORADO CONNECT SER\u00C1 RESPONSABLE DE LOS DA\u00D1OS Y PERJUICIOS DIRECTOS, CONSECUENTES, ESPECIALES, INDIRECTOS, EJEMPLARES O PUNITIVOS QUE PUEDAN SURGIR, YA SEA EN CONTRATO, EXTRACONTRACUALES O COMO PARTE DE CUALQUIER OTRA TEOR\u00CDA LEGAL, EN RELACI\u00D3N CON SU ACCESO AL SITIO O EL USO DE SERVICIOS, AUN CUANDO SE HAYA ADVERTIDO A COLORADO CONNECT DE LA POSIBILIDAD DE TALES DA\u00D1OS Y PERJUICIOS Y A PESAR DE CUALQUIER FRACASO DEL PROP\u00D3SITO ESENCIAL O CUALQUIER REMEDIO LIMITADO. LA RESPONSABILIDAD GLOBAL DE COLORADO CONNECT POR LOS DA\u00D1OS Y PERJUICIOS QUE RESULTEN DE ESTE ACUERDO O SE RELACIONEN CON \u00C9L NO EXCEDER\u00C1 $250.");
        softAssert.assertEquals(ol11.getText().trim(), "RECONOCIMIENTO DE INDEMNIDAD. Por este medio, Usted otorga indemnidad, defiende y exime de responsabilidad a Colorado Connect y sus Afiliados, empleados, agentes, contratistas, cesionarios, licenciatarios y sucesores en inter\u00E9s (\u201CPartes Indemnes\u201D) de todos y cada uno de los reclamos, p\u00E9rdidas, responsabilidades, da\u00F1os y perjuicios, honorarios, gastos y costos (incluidos honorarios de abogados, costas, compensaciones por da\u00F1os e importes de acuerdos extrajudiciales) que resulten de cualquier reclamo o demanda contra cualquier Parte Indemne que se origine de Su acceso al Sitio o Su falta a cualquier t\u00E9rmino de este Acuerdo. Colorado Connect le dar\u00E1 aviso a Usted de cualquier reclamo o demanda, y Colorado Connect tendr\u00E1 el derecho de participar en la defensa de cualquier reclamo a su propio costo.");
        softAssert.assertEquals(ol12.getText().trim(), "POL\u00CDTICA DE PRIVACIDAD. La pol\u00EDtica de privacidad de Colorado Connect, una copia de la cual est\u00E1 disponible en (la \u201CPol\u00EDtica de Privacidad\u201D), est\u00E1 incorporada a este Acuerdo mediante referencia. Al aceptar este Acuerdo, Usted acepta expresamente el uso y acceso a su informaci\u00F3n de identificaci\u00F3n personal y a otros datos seg\u00FAn se describe en la Pol\u00EDtica de Privacidad.");
        softAssert.assertEquals(ol13.getText().trim(), "SITIOS VINCULADOS. El Sitio contiene enlaces a sitios de terceros que no est\u00E1n bajo el control de Colorado Connect, y Colorado Connect no se hace responsable de ning\u00FAn contenido encontrado en ninguno de los sitios vinculados. Si desde el Sitio accede a un sitio de terceros, lo har\u00E1 bajo su propio riesgo. Colorado Connect proporciona enlaces solamente para facilidad de uso, y la inclusi\u00F3n de los enlaces no implica que Colorado Connect respalde o acepte responsabilidad alguna por el contenido de esos sitios de terceros. Colorado Connect acepta con agrado los enlaces hacia el Sitio. Usted puede establecer un enlace a este Sitio, a condici\u00F3n de que tal enlace no indique o implique ning\u00FAn patrocinio o respaldo a su sitio por parte de Colorado Connect o su sitio no respalde o se oponga a ning\u00FAn candidato a un cargo p\u00FAblico. Usted no podr\u00E1 utilizar en su sitio ning\u00FAn Contenido o Marcas que aparezcan en el Sitio al establecer el enlace. No podr\u00E1 incluir en marcos ni incorporar de otra forma en otro sitio el Contenido u otros materiales del Sitio, sin previo consentimiento escrito de Colorado Connect.");
        softAssert.assertEquals(ol14.getText().trim(), "AVISOS. A menos que se indique expresamente otra cosa, cualquier aviso exigido o permitido conforme a los t\u00E9rminos de este Acuerdo se dar\u00E1 a Colorado Connect por correo postal al domicilio de Colorado Connect mencionado en el Sitio. Si la ley respectiva exige que Colorado Connect acepte avisos por correo electr\u00F3nico (aunque no de otra manera), Usted podr\u00E1 enviar a Colorado Connect el aviso por correo electr\u00F3nico a trav\u00E9s de la p\u00E1gina \u201CP\u00F3ngase en contacto\u201D. En cada p\u00E1gina del Sitio hay un enlace a la p\u00E1gina \u201CP\u00F3ngase en contacto\u201D. Con respecto a los avisos de Colorado Connect a Usted, Colorado Connect puede notificarle sobre modificaciones public\u00E1ndolas en el Sitio, y al momento de tal publicaci\u00F3n todo cambio se considerar\u00E1 aviso efectivo seg\u00FAn lo dispuesto en la Secci\u00F3n 15.6. Usted acepta investigar los cambios.");
        softAssert.assertEquals(ol15.getText().trim(), "T\u00C9RMINOS GENERALES.\n" +
                " \n" +
                "15.1 Terceros beneficiarios. Conforme a los t\u00E9rminos de este Acuerdo, los afiliados de Colorado Connect son terceros beneficiarios, con derecho a hacer cumplir las disposiciones que ata\u00F1an directamente al Contenido sobre el cual tienen derecho.\n" +
                " \n" +
                "15.2 No asignaci\u00F3n. No podr\u00E1 asignar ni transferir ninguno de Sus derechos en virtud del presente, y cualquier intento de hacerlo ser\u00E1 nulo y sin efecto.\n" +
                " \n" +
                "15.3 Integraci\u00F3n. Este Acuerdo establece la comprensi\u00F3n total de las partes y sustituye a todos y cada uno de los acuerdos anteriores entre las partes, orales y escritos, respecto al tema de este Acuerdo. Este Acuerdo no se puede modificar, excepto mediante acuerdo mutuo por escrito de ambas partes. La exenci\u00F3n de cualquiera de las partes respecto a una infracci\u00F3n a alguna disposici\u00F3n de este Acuerdo no funcionar\u00E1 ni ser\u00E1 interpretada como exenci\u00F3n respecto a cualquier otra infracci\u00F3n presente o subsecuente.\n" +
                " \n" +
                "15.4 Separabilidad. Si por alguna raz\u00F3n una disposici\u00F3n de este Acuerdo se considera inv\u00E1lida o inaplicable, en todo o en parte, en alguna jurisdicci\u00F3n, tal disposici\u00F3n ser\u00E1 inv\u00E1lida respecto a tal jurisdicci\u00F3n, en el grado de tal invalidez o inaplicabilidad, sin que se afecten de ninguna manera su validez o aplicabilidad en cualquier otra jurisdicci\u00F3n, ni las dem\u00E1s disposiciones del presente en cualquier jurisdicci\u00F3n.\n" +
                " \n" +
                "15.5 Jurisdicci\u00F3n y lugar. Este Acuerdo estar\u00E1 regido por las leyes del Estado de Colorado, sin dar efecto a ning\u00FAn conflicto de principios jur\u00EDdicos. Las partes eximen al Acuerdo, espec\u00EDficamente, de la aplicaci\u00F3n de la Convenci\u00F3n de las Naciones Unidas sobre Contratos para la Venta Internacional de Bienes y de la Ley General de Intercambio de Informaci\u00F3n de Computadora. Por este medio, Usted se adscribe incondicional e irrevocablemente a la jurisdicci\u00F3n y el lugar del Estado y los tribunales federales que tienen su sede en Denver, Colorado. En cualquier conflicto, la parte que prevalezca tendr\u00E1 derecho a recuperar, a costa de la otra parte, los honorarios, costos y gastos razonables de sus abogados.\n" +
                " \n" +
                "15.6 Modificaciones. Colorado Connect se reserva el derecho, en cualquier momento y sin aviso, de a\u00F1adir, cambiar, actualizar o modificar el Sitio y estos t\u00E9rminos de uso, simplemente publicando tal adici\u00F3n, cambio, actualizaci\u00F3n o modificaci\u00F3n en este Sitio. Cualquier adici\u00F3n, cambio, actualizaci\u00F3n o modificaci\u00F3n tendr\u00E1 vigencia inmediata a partir de la publicaci\u00F3n en el Sitio.");
        softAssert.assertAll();

    }

    private void verifyEnglish() {

        softAssert.assertEquals(title.getText(), "Terms of Use");
        softAssert.assertEquals(p1.getText(), "Welcome to the websites of Colorado Connect (the \u201CSite\u201D). The Site is operated by the Connect for Health Colorado Company, a Colorado corporation doing business as Colorado Connect, (\u201CWe\u201D or \u201CUs\u201D). Please carefully read these Terms of Use. By using the Site, you acknowledge and agree that you have read and agree to be bound by these Terms of Use (this \u201CAgreement\u201D). This Agreement is made between Colorado Connect and You or, in the case that you represent and are using the Site on behalf of a company or other entity, that company or other entity (\u201CYou\u201D). IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, PLEASE EXIT THE SITE NOW AND REFRAIN FROM USING ANY MATERIAL THAT YOU MAY HAVE DOWNLOADED FROM THE SITE.");
        softAssert.assertEquals(ol1.getText().trim(), "USE OF THE SITE. All use of the Site is subject to the terms of this Agreement. You may access and use the Site solely for lawful purposes. You must be 13 years or older to use the Site. Colorado Connect reserves the right at any time and in its sole discretion to modify, suspend, or discontinue the Site (or any portion thereof) with or without notice.");
        softAssert.assertEquals(ol2.getText().trim(), "REGISTRATION. To access some areas of the Site, You may have to apply for and be approved as a registered user (a \u201CRegistered User\u201D) of the Site. Your approval as a Registered User is at the sole discretion of Colorado Connect. Upon approval as a Registered User, You may be asked to create a password-protected account (an \u201CAccount\u201D). You agree to keep your Account information and password confidential. You agree to notify Colorado Connect immediately of any actual or suspected unauthorized use of your Account. You are solely responsible for all activities that occur through Your Account. Colorado Connect will not be responsible for any loss to You caused by your failure to comply with these obligations. In connection with your application to become a Registered User, You will be asked to submit certain information about yourself (\u201CRegistration Information\u201D). You represent and warrant that: (a) all Registration Information You provide is true, accurate, current, and complete; and (b) You will maintain and promptly update the Registration Information to keep it true, accurate, current, and complete. As part of the registration process, You may be assigned or permitted to create a user ID for use in identifying your Account (a \u201CUser ID\u201D). You may not: (i) select or use a User ID of another person with the intent to impersonate that person; (ii) use a User ID in which another person has rights without such person\u2019s authorization; or (iii) use a User ID that Colorado Connect, in its sole discretion, deems offensive. Failure to comply with the foregoing shall constitute a breach of this Agreement, which may result in immediate termination of your Account.");
        softAssert.assertEquals(ol3.getText().trim(), "TERM AND TERMINATION. This Agreement will be effective on the date You first use the Site and will continue until terminated. Colorado Connect may terminate or modify this Agreement immediately, for any reason or no reason, with or without notice to You. You may terminate this Agreement upon written notice to Colorado Connect, such termination effective upon receipt of such notice by Colorado Connect. Colorado Connect may also suspend your use of the Site or deactivate a User ID and direct You to cease using the Site with or without notice to You and with or without cause. Upon any termination of this Agreement, all rights granted to You under this Agreement will cease and You must promptly discontinue all access to any part of the Site and the use of any Content downloaded or otherwise obtained from the Site. Sections 3, 4, 5, 7, 10, 11, and 15 will survive termination or expiration of this Agreement for any reason as they apply to the rights granted to Colorado Connect and the restrictions placed on You.");
        softAssert.assertEquals(ol4.getText().trim(), "CONTENT. The Site and the entire contents of the Site, including, but not limited to, text, files, images, graphics, illustrations, audio, video, and photographs on or offered through the Site (collectively, \u201CContent\u201D) are protected by intellectual property rights, including, as applicable and without limitation, copyrights, trademarks, patents, and other proprietary and intellectual property rights (\u201CIntellectual Property Rights\u201D) of Colorado Connect or other third parties who have granted rights to Colorado Connect.");
        softAssert.assertEquals(ol5.getText().trim(), "USE OF THE CONTENT. Your access to or use of the Content is subject to the terms and conditions of this Agreement. You may use the Content only in the form provided on or through the Site solely for your own informational purposes. You may not use any Content for any commercial purpose or charge a fee or other consideration in exchange for the Content. You may not utilize the Content to sell, advertise, endorse, or otherwise promote any other service, product, or party. All use of the Content must be accompanied by an acknowledgment that the Content is owned by Colorado Connect. You must otherwise abide by all Intellectual Property Rights, notices, information, or restrictions contained on or in any Content. Unless otherwise noted on the Site, as between You and Colorado Connect, its partners, affiliates, and licensors (\u201CAffiliates\u201D), all Content is owned by Colorado Connect and its Affiliates. Except as stated in this Agreement, You are granted no licenses or rights, whether by implication, estoppel, or otherwise, in or to the Site or Content, or any Intellectual Property Rights therein or related thereto, and You may not modify, reproduce, perform, display, create derivative works from, republish, post, transmit, participate in the transfer or sale of, distribute, or in any way exploit any portion of the Site or Content without the prior written permission of Colorado Connect. If you would like to use the Content in a manner that is not expressly set forth in this Agreement, please contact us using the \u201CContact Us\u201D page.");
        softAssert.assertEquals(ol6.getText().trim(), "MARKS. Unless otherwise labeled, all trademarks, service marks, logos, banners, and page headers displayed on this Site (collectively, the \u201CMarks\u201D) are the property of Colorado Connect and its Affiliates. Except as expressly set forth in this Agreement, You may not display, link to, or otherwise use the Marks without the prior written permission of Colorado Connect.");
        softAssert.assertEquals(ol7.getText().trim(), "POSTINGS AND UPLOADS. The Site may include forums, bulletin boards, chat rooms, or other opportunities through which you may provide or upload Content of your own to the Site. You agree not to upload or provide any Content that is: (1) libelous, defamatory, obscene, abusive, pornographic, threatening, or an invasion of privacy; (2) an infringement of the Intellectual Property Rights of any third party; (3) illegal in any way or that advocates illegal activity; (4) an advertisement or solicitation of funds, goods, or services; (5) an endorsement or advertisement for any candidate for public office; (6) a software virus or contains any other harmful computer code, files, or programs. We reserve the right to refuse to post or remove any post or Content which in our sole discretion violates this Section 7 without prior notice. You hereby represent and warrant to Colorado Connect and its Affiliates that You own all right, title, and interest in and to any Content that You provide or upload to the Site, or that You have sufficient rights, whether by implication, estoppel, or otherwise, to post or upload Content and to grant Colorado Connect the rights discussed in this Section 7. You will indemnify, defend, and hold harmless Colorado Connect and its Affiliates from any and all third-party claims, losses, liabilities, damages, fees, expenses, and costs (including attorneys\u2019 fees and court costs) that result from a breach or alleged breach of any representation or warranty set forth in Section 7. By providing or uploading any Content to the Site, You grant Colorado Connect a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, copy, store, reproduce, modify, display, adapt, publish, translate, create derivative works from, distribute, and display such Content throughout the world in any form, media, software, or technology of any kind. In addition, you waive all moral rights in the Content, including any Content you post or upload, or warrant that all moral rights applicable to such Content have been waived. You also grant Colorado Connect the right to use Your name in connection with the reproduction or distribution of such material.");
        softAssert.assertEquals(ol8.getText().trim(), "CLAIMS OF INFRINGEMENT. Just as Colorado Connect requires users of the Site to respect the copyrights and other intellectual property rights of Colorado Connect, its Affiliates, and other third parties, Colorado Connect respects the copyrights and other intellectual property rights of users of the Site and other third parties. If You believe in good faith that Your copyrighted work has been reproduced on the Site without authorization in a way that constitutes copyright infringement, You may notify our designated copyright agent by mail to:\n" +
                " \n" +
                "Colorado Connect\n" +
                "c/o Connect for Health Colorado\n" +
                "4600 S. Ulster Street, Suite 300\n" +
                "Denver, CO 80237\n" +
                "Please provide the following information to Colorado Connect:\n" +
                "(1) The identity of the infringed work, and of the allegedly infringing work;\n" +
                "(2) Your name, address, daytime phone number, and Email address, if available;\n" +
                "(3) A statement that You have a good-faith belief that the use of the copyrighted work is not authorized by the owner, his or her agent, or the law;\n" +
                "(4) A statement of the accuracy of the notice and, under penalty of perjury, that You are authorized to act on behalf of the owner; and\n" +
                "(5) Your electronic or physical signature.");
        softAssert.assertEquals(ol9.getText().trim(), "REPRESENTATIONS AND WARRANTIES. You hereby represent, warrant, and covenant for the benefit of Colorado Connect and its Affiliates that: (1) You have the legal right and authority to enter into this Agreement, and, if You are accepting this Agreement on behalf of a company or other entity, to bind the company or other entity to the terms of this Agreement; (2) You have the legal right and authority to perform Your obligations under this Agreement and to grant the rights and licenses described in this Agreement and in any applicable additional agreement You enter into in connection with any of the Services; (3) all information You provide to Colorado Connect in connection with this Agreement and Your access to the Site and use of the Services is correct and current.");
        softAssert.assertEquals(ol10.getText().trim(), "DISCLAIMER AND LIMITATION OF LIABILITY.\n" +
                " \n" +
                "10.1 Disclaimer. THE SITE IS PROVIDED BY Colorado Connect \u201CAS IS\u201D and \u201CAS AVAILABLE\u201D WITH NO WARRANTIES WHATSOEVER. NEITHER Colorado Connect NOR ITS AFFILIATES REPRESENT OR ENDORSE THE ACCURACY OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT, OR OTHER INFORMATION DISPLAYED, DOWNLOADED FROM, OR DISTRIBUTED THROUGH THE SITE. YOU AGREE THAT YOUR ACCESS TO THE SITE IS AT YOUR OWN RISK AND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY LIABILITY OR DAMAGE YOU INCUR THROUGH ACCESS TO THE SITE. EXCEPT WHERE THE LAWS AND REGULATIONS OF A PARTICULAR JURISDICTION CONCERNING WARRANTIES CANNOT BE WAIVED OR EXCLUDED BY AGREEMENT, COLORADO CONNECT EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, REGARDING THE SITE, INCLUDING, WITHOUT LIMITATION, ALL WARRANTIES OF TITLE, NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE. YOU RECOGNIZE THAT THE CURRENT STATE OF TECHNOLOGY DOES NOT ALLOW FOR ERROR-FREE ACCESS TO THE SITE AND INTERRUPTIONS, CRASHES, AND DOWNTIME BEYOND COLORADO CONNECT\u2019S CONTROL MAY OCCUR FROM TIME TO TIME.\n" +
                " \n" +
                "10.2 Limitation. IN NO EVENT WILL COLORADO CONNECT BE LIABLE FOR ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, EXEMPLARY, OR PUNITIVE DAMAGES, WHETHER IN CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, IN CONNECTION WITH YOUR ACCESS TO THE SITE OR USE OF THE SERVICES, EVEN IF COLORADO CONNECT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OR ANY LIMITED REMEDY. COLORADO CONNECT\u2019S TOTAL AGGREGATE LIABILITY FOR ANY DAMAGES ARISING OUT OF OR RELATED TO THIS AGREEMENT WILL NOT EXCEED $250.");
        softAssert.assertEquals(ol11.getText().trim(), "INDEMNIFICATION. You hereby indemnify, defend, and hold harmless Colorado Connect and its Affiliates, employees, agents, contractors, assigns, licensees, and successors in interest (\u201CIndemnified Parties\u201D) from any and all claims, losses, liabilities, damages, fees, expenses, and costs (including attorneys\u2019 fees, court costs, damage awards, and settlement amounts) that result from any claim or allegation against any Indemnified Party arising from Your accessing the Site or Your breach of any term of this Agreement. Colorado Connect will provide You with notice of any such claim or allegation, and Colorado Connect will have the right to participate in the defense of any such claim at its expense.");
        softAssert.assertEquals(ol12.getText().trim(), "PRIVACY POLICY. Colorado Connect\u2019s privacy policy, a copy of which is available at (the \u201CPrivacy Policy\u201D), is incorporated in this Agreement by reference. By accepting this Agreement, You expressly consent to the use and disclosure of your personally identifiable and other information as described in the Privacy Policy.");
        softAssert.assertEquals(ol13.getText().trim(), "LINKED SITES. The Site contains links to third-party sites that are not under the control of Colorado Connect, and Colorado Connect is not responsible for any content on any linked site. If you access a third-party site from the Site, then you do so at your own risk. Colorado Connect provides links only as a convenience, and the inclusion of the link does not imply that Colorado Connect endorses or accepts any responsibility for the content on those third-party sites. Colorado Connect welcomes links to the Site. You may establish a link to this Site, provided that the link does not state or imply any sponsorship or endorsement of your site by Colorado Connect or your site does not endorse or oppose any candidate for public office. You may not use on your site, any Content or Marks appearing on the Site in establishing the link. You may not frame or otherwise incorporate into another site the Content or other materials on the Site without prior written consent of Colorado Connect.");
        softAssert.assertEquals(ol14.getText().trim(), "NOTICES. Except as expressly stated otherwise, any notices required or allowed under this Agreement will be given to Colorado Connect by postal mail to the address for Colorado Connect listed on the Site. If applicable law requires that Colorado Connect accepts email notices (but not otherwise), then You may send Colorado Connect email notice using the \u201CContact Us\u201D page. A link to the Contact Us page is available on each page of the Site. With respect to Colorado Connect\u2019s notices to You, Colorado Connect may provide notice of amendments by posting them on the Site and upon such posting any amendment shall be deemed effective notice as set forth in Section 15.6. You agree to check for changes.");
        softAssert.assertEquals(ol15.getText().trim(), "GENERAL TERMS.\n" +
                " \n" +
                "15.1 Third-Party Beneficiaries. Colorado Connect\u2019s Affiliates are intended third-party beneficiaries under this Agreement with the right to enforce the provisions that directly concern Content to which they have rights.\n" +
                " \n" +
                "15.2 Nonassignment. You may not assign or transfer any of Your rights hereunder, and any attempt to do so will be null and void.\n" +
                " \n" +
                "15.3 Integration. This Agreement sets forth the entire understanding of the parties and supersedes any and all prior oral and written agreements or understandings between the parties regarding the subject matter of this Agreement. This Agreement may not be modified except upon mutual written agreement of both parties. The waiver by either party of a breach of any provision of this Agreement will not operate or be interpreted as a waiver of any other or subsequent breach.\n" +
                " \n" +
                "15.4 Severability. If for any reason any provision of this Agreement shall be held invalid or unenforceable in whole or in part in any jurisdiction, such provision shall, as to such jurisdiction, be ineffective to the extent of such invalidity or unenforceability, without in any manner affecting the validity or enforceability thereof in any other jurisdiction or the remaining provisions hereof in any jurisdiction.\n" +
                " \n" +
                "15.5 Jurisdiction and Venue. This Agreement will be governed by the laws of the State of Colorado, without giving effect to any conflict of laws principles. The parties specifically exclude from application to the Agreement the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transactions Act. You hereby irrevocably and unconditionally consent to the jurisdiction and venue in the state and federal courts sitting in Denver, Colo. In any such dispute, the prevailing party will be entitled to recover its reasonable attorneys\u2019 fees and expenses from the other party.\n" +
                " \n" +
                "15.6 Modifications. Colorado Connect reserves the right, at any time and without notice, to add to, change, update, or modify the site and these Terms of Use, simply by posting such addition, change, update, or modification on this site. Any such addition, change, update, or modification will be effective immediately upon posting on the Site.");
        softAssert.assertAll();

    }
}
